version: '3.8'

services:
  lita-container:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    privileged: true
    environment:
      - TZ=Asia/Seoul
      - NVIDIA_VISIBLE_DEVICES=all  # Use all available GPUs dynamically
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "2422:22"  # SSH 접근을 위한 포트 매핑
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Use all available GPUs
              capabilities: [gpu]
    tmpfs:
      - /sys/kernel/debug
      - /sys/kernel/debug/tracing